<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--JavaScript at end of body for optimized loading-->
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
  </head>

<div>
  <body class="brown darken-1" style="background-repeat:no-repeat;background-size:cover;">
    <nav>
    <div class="nav-wrapper brown lighten-1">
      <a href="#" class="brand-logo right">
        <?php
        session_start();
        echo $_SESSION["username"];
        ?></a>

        <a href="#" class="brand-logo right" style="font-family:georgia;text-align:center"></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><a>
          <?php
          session_start();
          if($_SESSION['username'] == true) {
            echo '<a href="logout.php"><span>Logout</span></a>';
          }
          else {
            echo '<a href="login.php"><span>Login</span></a>';
          }
          ?>
      </a></li>
      </ul>
    </div>
  </nav>

    <div class="amber-text text-lighten-5" style="font-family:georgia;text-align:center;background-size:cover;">

              <h1 style="">Tattered Pages</h1>
              <h4>Find your book
              <a class="btn-floating btn-large waves-effect waves-light brown darken-1" href="addNewBook.phtml"><i class="material-icons">add</i></a>
              </h4>
              <div class="row">
                <div class="col s5 offset-s4">
                  <form class="" action="" method="post">
                    <table>
                      <tr>
                        <td style="text-align:center;">
                          <input type="text" name="search" placeholder="Search....">
                        </td><td><button class="btn-floating btn-large waves-effect waves-light brown darken-1" type="submit" name="submit"><i class="material-icons prefix">search</i></button></td>
                      </tr>
                    </table>
                    </form>
                    <?php
                    $search = $_POST["search"];
                    include('config.php');
                    if(isset($_POST['submit'])){
                    $sql = "SELECT * FROM myDB.Books WHERE Book LIKE '%".$search."%' OR Author LIKE '%".$search."%'
                   OR Genre LIKE '%".$search."%'";
                    $result = mysqli_query($conn,$sql);
                    if (!mysqli_query($conn,$sql)){
                      die('Error: ' . mysqli_error($conn));
                    }
                    else{
                      while($row = $result->fetch_assoc()){
                        ?>
                       <br>
                       <br>
                       <br>
                       <table>
                         <tr>
                           <td style="font-size:20px;font-family:georgia;color:white;">
                             <?php
                             echo "<a href='book.phtml?Book=".$row['Book']."'>".$row['Book']." || ".$row['Author']." || ".$row['Genre'];
                             ?>
                           </a>
                           </td>
                         </tr>
                       </table>
                       <?php
                      }
                    }
                  }
                  ?>
                </div>
              </div>
          </div>
  </body>
</div>
<style>/* label color */
   .input-field label {
     color: white;
   }
   /* label focus color */
   .input-field input[type=text]:focus + label {
     color: white;
   }
   /* label underline focus color */
   .input-field input[type=text]:focus {
     text-shadow:white;
     border-bottom: 1px white;
     box-shadow: 0 1px 0 0 white;
   }
   /* valid color */
   .input-field input[type=text].valid {
     border-bottom: 1px white;
     box-shadow: 0 1px 0 0 white;
   }
   /* invalid color */
   .input-field input[type=text].invalid {
     border-bottom: 1px white;
     box-shadow: 0 1px 0 0 white;
   }
   /* icon prefix focus color */
   .input-field .prefix.active {
     color: white;
   }
   .input-field .prefix {
       position: absolute;
       width: 3rem;
       font-size: 2rem;
       -webkit-transition: color .2s;
       transition: color .2s;
       top: .5rem;
       right:0;
   }
 </style>
 <script>document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.sidenav');
    var instances = M.Sidenav.init(elems, options);
  });

  // Or with jQuery

  $(document).ready(function(){
    $('.sidenav').sidenav();
  });</script>
</html>
<?php

 ?>
