<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--JavaScript at end of body for optimized loading-->
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
  </head>

  <body class="brown darken-1">

      <!--JavaScript at end of body for optimized loading-->
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>

  <div style="font-family:georgia;text-align:center;color:white;">

    <h1>BOOK REVIEW</h1>
    <div class="row">
        <div class="col s4  offset-s2">

          <div class="card">
            <div class="card-content">
              <span class="card-title" style="color:black;text-align:left">Login</span>
              <br>
              <div class="row">
                <form class="col s12" action="verifyEmail.php" method="post">

                  <div class="row" style="text-align:center">
                    <div class="input-field col s6">
                      <input placeholder="" name="email" type="text" class="validate">
                      <label for="first_name">Email</label>
                    </div>
                  </div>

              </div>
            </div>

            <div class="card-action">
              <button class="btn waves-effect brown" type="submit">Submit
                </a><i class="material-icons right">send</i>
              </button>

            </div>
            </form>
          </div>
        </div>
      </div>
      </div>
    </body>
    </html>
